import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.157.0/build/three.module.js';

export const ThreeImports = {
    // For GLTFLoader
    AnimationClip: THREE.AnimationClip,
    Bone: THREE.Bone,
    Box3: THREE.Box3,
    BufferAttribute: THREE.BufferAttribute,
    BufferGeometry: THREE.BufferGeometry,
    ClampToEdgeWrapping: THREE.ClampToEdgeWrapping,
    Color: THREE.Color,
    ColorManagement: THREE.ColorManagement,
    DirectionalLight: THREE.DirectionalLight,
    DoubleSide: THREE.DoubleSide,
    FileLoader: THREE.FileLoader,
    FrontSide: THREE.FrontSide,
    Group: THREE.Group,
    ImageBitmapLoader: THREE.ImageBitmapLoader,
    InstancedMesh: THREE.InstancedMesh,
    InterleavedBuffer: THREE.InterleavedBuffer,
    InterleavedBufferAttribute: THREE.InterleavedBufferAttribute,
    Interpolant: THREE.Interpolant,
    InterpolateDiscrete: THREE.InterpolateDiscrete,
    InterpolateLinear: THREE.InterpolateLinear,
    Line: THREE.Line,
    LineBasicMaterial: THREE.LineBasicMaterial,
    LineLoop: THREE.LineLoop,
    LineSegments: THREE.LineSegments,
    LinearFilter: THREE.LinearFilter,
    LinearMipmapLinearFilter: THREE.LinearMipmapLinearFilter,
    LinearMipmapNearestFilter: THREE.LinearMipmapNearestFilter,
    LinearSRGBColorSpace: THREE.LinearSRGBColorSpace,
    Loader: THREE.Loader,
    LoaderUtils: THREE.LoaderUtils,
    Material: THREE.Material,
    MathUtils: THREE.MathUtils,
    Matrix4: THREE.Matrix4,
    Mesh: THREE.Mesh,
    MeshBasicMaterial: THREE.MeshBasicMaterial,
    MeshPhysicalMaterial: THREE.MeshPhysicalMaterial,
    MeshStandardMaterial: THREE.MeshStandardMaterial,
    MirroredRepeatWrapping: THREE.MirroredRepeatWrapping,
    NearestFilter: THREE.NearestFilter,
    NearestMipmapLinearFilter: THREE.NearestMipmapLinearFilter,
    NearestMipmapNearestFilter: THREE.NearestMipmapNearestFilter,
    NumberKeyframeTrack: THREE.NumberKeyframeTrack,
    Object3D: THREE.Object3D,
    OrthographicCamera: THREE.OrthographicCamera,
    PerspectiveCamera: THREE.PerspectiveCamera,
    PointLight: THREE.PointLight,
    Points: THREE.Points,
    PointsMaterial: THREE.PointsMaterial,
    PropertyBinding: THREE.PropertyBinding,
    Quaternion: THREE.Quaternion,
    QuaternionKeyframeTrack: THREE.QuaternionKeyframeTrack,
    RepeatWrapping: THREE.RepeatWrapping,
    Skeleton: THREE.Skeleton,
    SkinnedMesh: THREE.SkinnedMesh,
    Sphere: THREE.Sphere,
    SpotLight: THREE.SpotLight,
    Texture: THREE.Texture,
    TextureLoader: THREE.TextureLoader,
    TriangleFanDrawMode: THREE.TriangleFanDrawMode,
    TriangleStripDrawMode: THREE.TriangleStripDrawMode,
    Vector2: THREE.Vector2,
    Vector3: THREE.Vector3,
    VectorKeyframeTrack: THREE.VectorKeyframeTrack,
    SRGBColorSpace: THREE.SRGBColorSpace,
    InstancedBufferAttribute: THREE.InstancedBufferAttribute,
  
    // For BufferGeometry
    BufferAttribute: THREE.BufferAttribute,
    Float32BufferAttribute: THREE.Float32BufferAttribute,
    InstancedBufferAttribute: THREE.InstancedBufferAttribute,
    InterleavedBuffer: THREE.InterleavedBuffer,
    InterleavedBufferAttribute: THREE.InterleavedBufferAttribute,
    TriangleFanDrawMode: THREE.TriangleFanDrawMode,
    TriangleStripDrawMode: THREE.TriangleStripDrawMode,
    TrianglesDrawMode: THREE.TrianglesDrawMode,
  };
  